apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1070960482-deployment
  labels:
    app: alex-1070960482
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alex-1070960482
  template:
    metadata:
      labels:
        app: alex-1070960482
    spec:
      containers:
      - name: contenedor-1070960482
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/a1070960482:latest
        ports:
        - containerPort: 5000
